[package]
name = "rocket-krb5"
version = "0.1.0"
edition = "2024"

[dependencies]
rocket = { version = "0.5.1", features = ["json"] }
libgssapi = { version = "0.9.1" }
base64 = { version = "0.22.1" }
