[package]
name = "librping"
version = "0.1.0"
edition = "2024"

[dependencies]
hostname = "0.4.1"
reqwest = { version = "0.12.23", features = ["json"] }
serde_json = "1.0.143"
tabled = "0.20.0"
libgssapi = { version = "0.9.1" }
base64 = { version = "0.22.1" }
